#cloud-config

package_update: true

packages:
  - apache2

write_files:
  - path: /var/www/html/index.html
    permissions: '0644'
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Cloud Services Week 7</title>
      </head>
      <body>
        <h1>${page_message}</h1>
        <p>Iago Prol González</p>
        <p>This web server was automatically configured with cloud-init.</p>
      </body>
      </html>

runcmd:
  - systemctl enable apache2
  - systemctl restart apache2
